# NUMPY

In [1]:
import numpy as np

In [2]:
np.__version__

'2.1.3'

In [3]:
import sys 
sys.version

'3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:37:03) [MSC v.1929 64 bit (AMD64)]'

## creating List

In [4]:
my_list = [ 0,1,2,3,4,5 ]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

### converting from list to array

In [6]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [8]:
np.          # numpy as many function , we learn only important functions

SyntaxError: invalid syntax (1061051750.py, line 1)

In [9]:
np.arange(10)                  # 1D array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [11]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [12]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
np.arange(20,10)            # 1st arg < 2nd arg

array([], dtype=int64)

In [14]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [15]:
np.arange(-15,10)

array([-15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,
        -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [16]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [17]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [18]:
np.arange(0,30,5)               # step counting

array([ 0,  5, 10, 15, 20, 25])

In [19]:
np.arange(0,10,2,2)                # it accepts only 3 arguments

TypeError: Cannot interpret '2' as a data type

In [20]:
np.zeros(10)                       # parameter tuning 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros(10,dtype=int)             

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
np.zeros((2,2),dtype=int)               # 2 dimensions

array([[0, 0],
       [0, 0]])

In [23]:
np.zeros((2,10))                       # 2 rows and 10 columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
np.zeros((10,10),dtype=int)                  # 10 x 10 matrix (10 rows and 10 columns)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [25]:
np.ones(3)

array([1., 1., 1.])

In [26]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.ones((3,3),dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [28]:
np.ones((5,3),dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [29]:
rand(3)                        # rand is a function

NameError: name 'rand' is not defined

In [30]:
random.rand(3)            # random is a module

NameError: name 'random' is not defined

In [31]:
np.random.rand(4)                 # ex == otp

array([0.98932362, 0.28785802, 0.8076027 , 0.73288275])

In [32]:
np.random.rand(3,5)              # np --- package , random = module ,rand = fn

array([[0.28754742, 0.01829849, 0.66416193, 0.332731  , 0.57864859],
       [0.71521311, 0.29518457, 0.1645106 , 0.33689778, 0.28900701],
       [0.17698961, 0.14538267, 0.03135986, 0.4512541 , 0.68520714]])

In [33]:

np.random.randint(3,5)        # it generates the random number between the 3 and 5

3

In [34]:
np.random.randint(2,20,4) 

array([15, 13,  2, 15], dtype=int32)

In [35]:
np.random.randint( -30,20,10)

array([ -9,  18,  -9, -27,   8, -12,   7,  -3,  13,  17], dtype=int32)

In [36]:
np.random.randint(10,40,(10,10))       # random values from 10 - 40 (10 rows and 10 columns)

array([[16, 18, 36, 16, 24, 11, 29, 10, 32, 34],
       [18, 20, 36, 16, 19, 19, 22, 32, 25, 20],
       [20, 14, 26, 15, 39, 29, 33, 27, 13, 17],
       [16, 14, 18, 32, 26, 38, 28, 25, 21, 10],
       [18, 36, 31, 26, 38, 17, 19, 16, 24, 37],
       [36, 18, 36, 15, 24, 12, 19, 32, 29, 20],
       [13, 33, 32, 37, 38, 11, 16, 10, 13, 18],
       [34, 24, 12, 28, 13, 35, 34, 11, 17, 24],
       [34, 39, 20, 14, 37, 15, 21, 36, 35, 39],
       [18, 36, 15, 26, 10, 35, 33, 24, 34, 33]], dtype=int32)

In [37]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [38]:
np.arange(1,13).reshape(3,4)         

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
np.arange(1,13).reshape(4,3)    

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [40]:
np.arange(1,13).reshape(12,1)    

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [41]:
np.arange(1,13).reshape(1,12)    

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

## Slicing in matrix

In [42]:
b = np.random.randint(10,20,(5,4))
b

array([[18, 18, 15, 14],
       [15, 10, 14, 13],
       [12, 17, 17, 12],
       [14, 19, 19, 12],
       [11, 13, 19, 17]], dtype=int32)

In [43]:
type(b)

numpy.ndarray

In [44]:
b[:]

array([[18, 18, 15, 14],
       [15, 10, 14, 13],
       [12, 17, 17, 12],
       [14, 19, 19, 12],
       [11, 13, 19, 17]], dtype=int32)

In [45]:
b[1:3]              # in array slicing , it will print only the rows

array([[15, 10, 14, 13],
       [12, 17, 17, 12]], dtype=int32)

In [46]:
b[1,2]           # the specific value

np.int32(14)

In [47]:
b[2,3]

np.int32(12)

In [48]:
b[1,-2]

np.int32(14)

In [49]:
b[1:2]

array([[15, 10, 14, 13]], dtype=int32)

In [50]:
b[-5,3]

np.int32(14)

## Numpy operations

In [51]:
arr

array([0, 1, 2, 3, 4, 5])

In [52]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[79, 12, 77, 49, 11, 71, 60, 23, 63, 53],
       [53, 98, 31, 40, 31, 32, 29, 85, 57, 23],
       [25, 62, 85, 76, 97, 93, 21, 89, 23, 76],
       [60, 99, 27, 54, 23, 49, 44,  2, 89, 66],
       [31,  1, 97, 22,  1, 59, 85, 48, 41, 55],
       [99, 15, 58, 76, 58, 27, 89, 76, 63, 85],
       [89, 18, 27,  8, 67, 39, 77, 74, 65, 77],
       [25, 30, 97, 51, 17, 91, 98, 35, 25, 77],
       [73, 13, 84, 24, 72, 48, 53, 72, 78, 65],
       [83, 96, 48, 44, 70, 56, 57, 68, 28,  5]], dtype=int32)

In [53]:
arr2[:]

array([[79, 12, 77, 49, 11, 71, 60, 23, 63, 53],
       [53, 98, 31, 40, 31, 32, 29, 85, 57, 23],
       [25, 62, 85, 76, 97, 93, 21, 89, 23, 76],
       [60, 99, 27, 54, 23, 49, 44,  2, 89, 66],
       [31,  1, 97, 22,  1, 59, 85, 48, 41, 55],
       [99, 15, 58, 76, 58, 27, 89, 76, 63, 85],
       [89, 18, 27,  8, 67, 39, 77, 74, 65, 77],
       [25, 30, 97, 51, 17, 91, 98, 35, 25, 77],
       [73, 13, 84, 24, 72, 48, 53, 72, 78, 65],
       [83, 96, 48, 44, 70, 56, 57, 68, 28,  5]], dtype=int32)

In [54]:
arr2 [ :: -1]

array([[83, 96, 48, 44, 70, 56, 57, 68, 28,  5],
       [73, 13, 84, 24, 72, 48, 53, 72, 78, 65],
       [25, 30, 97, 51, 17, 91, 98, 35, 25, 77],
       [89, 18, 27,  8, 67, 39, 77, 74, 65, 77],
       [99, 15, 58, 76, 58, 27, 89, 76, 63, 85],
       [31,  1, 97, 22,  1, 59, 85, 48, 41, 55],
       [60, 99, 27, 54, 23, 49, 44,  2, 89, 66],
       [25, 62, 85, 76, 97, 93, 21, 89, 23, 76],
       [53, 98, 31, 40, 31, 32, 29, 85, 57, 23],
       [79, 12, 77, 49, 11, 71, 60, 23, 63, 53]], dtype=int32)

In [55]:
arr2[::-2]

array([[83, 96, 48, 44, 70, 56, 57, 68, 28,  5],
       [25, 30, 97, 51, 17, 91, 98, 35, 25, 77],
       [99, 15, 58, 76, 58, 27, 89, 76, 63, 85],
       [60, 99, 27, 54, 23, 49, 44,  2, 89, 66],
       [53, 98, 31, 40, 31, 32, 29, 85, 57, 23]], dtype=int32)

In [56]:
arr

array([0, 1, 2, 3, 4, 5])

In [57]:
arr.max()

np.int64(5)

In [58]:
arr.min()

np.int64(0)

In [59]:
arr.mean()

np.float64(2.5)

In [60]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [61]:
from numpy import *                 # 256 functions are called internally 
a = array([1,2,3,4,9])
median(a)

np.float64(3.0)

### indexing 

In [62]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [63]:
row = 4
col = 5

In [64]:
col

5

In [65]:
row

4

In [66]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [67]:
mat[row,col]

np.int64(45)

In [68]:
mat[4,5]

np.int64(45)

In [69]:
print(row)
print(col)

4
5


In [70]:
col = 6                   # changed

In [71]:
mat[7]                   # bydefault it shows the 7th row

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [72]:
mat[:,col]            # column

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [73]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [74]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [75]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [76]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [77]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [78]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [79]:
mat[1:2,2:4]

array([[12, 13]])

In [80]:
mat[2:3,2:3]

array([[22]])

In [81]:
mat[2:3,4:5]

array([[24]])

In [82]:
mat[7:8,5:8]

array([[75, 76, 77]])

## Masking in numpy ( Filter )

In [83]:
id(mat)

1897999743184

In [84]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [85]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [86]:
mat [ mat > 50 ]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [87]:
mat [ mat == 50 ]

array([50])

In [88]:
mat[mat>=50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [89]:
mat[mat !=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

## identity

- it returns the 1 in principal diagonal and rest of the elements are 0

In [90]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [91]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## ndimensions,shape,size,itemsize,astype

In [92]:
A1 = np.arange(0,10)
A1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
A2 = np.arange(0,6).reshape(2,3)
A2

array([[0, 1, 2],
       [3, 4, 5]])

In [94]:
A1.ndim                           # returns the no.of dimensions 

1

In [95]:
A2.ndim

2

In [96]:
A1.shape                         # returns the no.of rows and columns

(10,)

In [97]:
A2.shape

(2, 3)

In [98]:
A1.size

10

In [99]:
A2.size                                 # no.of elements

6

In [100]:
A1.itemsize                               # it returns the memory size

8

In [101]:
A1.astype(float)                         # from one data type to another datatype

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### Scalar operations

- it includes add, sub,mul, mod, pow.

In [102]:
A3 = np.arange(12).reshape(3,4)
A3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
A3+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [104]:
A3 - 1

array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [105]:
A3 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [106]:
A3 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [107]:
A3 | 2

array([[ 2,  3,  2,  3],
       [ 6,  7,  6,  7],
       [10, 11, 10, 11]])

In [108]:
A3 % 2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

## relational operation

- performing these operation between the arrays ( 1d , 2d, 3d )

In [109]:
A3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [110]:
A4 = np.arange(10,22,dtype=int).reshape(3,4)
A4

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [111]:
A3>A4

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [112]:
A3<A4

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [113]:
A3 >= A4

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [114]:
A3 == A4

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [115]:
A3 != A4

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

## logs and exponentials

In [116]:
A3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [117]:
A4

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [118]:
np.exp(A4)

array([[2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05],
       [1.20260428e+06, 3.26901737e+06, 8.88611052e+06, 2.41549528e+07],
       [6.56599691e+07, 1.78482301e+08, 4.85165195e+08, 1.31881573e+09]])

In [119]:
np.log(A4)

array([[2.30258509, 2.39789527, 2.48490665, 2.56494936],
       [2.63905733, 2.7080502 , 2.77258872, 2.83321334],
       [2.89037176, 2.94443898, 2.99573227, 3.04452244]])

## Reshaping the methods in numpy

#### 1. transpose

- converting from rows to columns and columns to rows

In [120]:
P = np.arange(12).reshape(3,4)
P

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [121]:
P.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [122]:
P.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

#### 2 . Ravel 

- convert it any dimensions to one dimension

In [123]:
P.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### 3 . Stacking 

- joining the arrays of same dimensions
- stackings are 2 types
- 1 . vstack = vertical stack
- 2 . hstack = horizontal stack

In [124]:
P

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [125]:
P1 = np.arange(12,24).reshape(3,4)
P1

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [126]:
np.hstack((P,P1))                         # horizontal stack

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [127]:
np.vstack((P,P1))                      # vertical stack

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### 4 . Splitting

- opposite to the stacking 
- splitting are two types
- 1 . vsplit
- 2 . hsplit

In [128]:
P

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [129]:
np.hsplit(P,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [130]:
P1

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [131]:
np.vsplit(P1,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]